name: Deploy Docker image to GitHub Packages

on:
  push:
    branches: [master]

env:
  IMAGE_NAME: blog-graphql
  IMAGE_VERSION: latest
  DOCKERFILE_PATH: ./src/main/docker/Dockerfile.jvm
  GITHUB_PACKAGE_REGISTRY: ghcr.io
  GITHUB_REPOSITORY: zamarianpatrick/hftm-blog-graphql

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt'
          cache: 'maven'
          cache-url: 'https://github.com/actions/cache'

      - name: Cache Maven dependencies
        id: cache-maven
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn clean package

      - name: Login to GitHub Packages
        uses: docker/login-action@v1
        with:
          registry: ${{ env.GITHUB_PACKAGE_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}

      - name: Build Docker image
        run: docker build -t ${GITHUB_PACKAGE_REGISTRY}/${GITHUB_REPOSITORY#*/}/${IMAGE_NAME}:${IMAGE_VERSION} -f ${DOCKERFILE_PATH} .

      - name: Push Docker image to GitHub Packages
        run: docker push ${GITHUB_PACKAGE_REGISTRY}/${GITHUB_REPOSITORY#*/}/${IMAGE_NAME}:${IMAGE_VERSION}
