name: Deploy Docker image to GitHub Packages

on:
  push:
    branches: [master]

env:
  IMAGE_NAME: blog-graphql
  IMAGE_VERSION: latest
  DOCKERFILE_PATH: ./Dockerfile
  GITHUB_PACKAGE_REGISTRY: ghcr.io
  GITHUB_REPOSITORY: ZamarianPatrick/hftm-blog-graphql
  PACKAGE_NAME: ${GITHUB_PACKAGE_REGISTRY}/${GITHUB_REPOSITORY}/${IMAGE_NAME}:${IMAGE_VERSION}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'


      - name: Build with Maven
        run: mvn clean package

      - name: Login to GitHub Packages
        uses: docker/login-action@v1
        with:
          registry: ${{ env.GITHUB_PACKAGE_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}

      - name: Build Docker image
        run: docker build -t ${PACKAGE_NAME} -f ${DOCKERFILE_PATH} .

      - name: Push Docker image to GitHub Packages
        run: docker push ${PACKAGE_NAME}
